example-5: example-5.c
	gcc -g example-5.c -o example-5 \
        -lSDL2 -lSDL2_image -lSDL2_gfx -lSDL2_ttf\
		-I/opt/homebrew/Cellar/sdl2/2.32.10/include \
		-L/opt/homebrew/Cellar/sdl2/2.32.10/lib \
		-I/opt/homebrew/Cellar/sdl2/2.32.10/include/SDL2 \
		-L/opt/homebrew/Cellar/sdl2_image/2.8.8/lib \
		-I/opt/homebrew/Cellar/sdl2_image/2.8.8/include 
        -I/opt/homebrew/Cellar/sdl2_ttf/2.24.0/include \
		-L/opt/homebrew/Cellar/sdl2_ttf/2.24.0/lib \
        -I/opt/homebrew/Cellar/sdl2_gfx/1.0.4/include \
        -L/opt/homebrew/Cellar/sdl2_gfx/1.0.4/lib \


