/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ship_movement.proto */

#ifndef PROTOBUF_C_ship_5fmovement_2eproto__INCLUDED
#define PROTOBUF_C_ship_5fmovement_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Connect Connect;
typedef struct _Movement Movement;
typedef struct _ServerResponse ServerResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * Message to connect (replaces "CONNECT %c")
 */
struct  _Connect
{
  ProtobufCMessage base;
  char *client_id;
};
#define CONNECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connect__descriptor) \
    , NULL }


/*
 * Message to move (replaces "MOVE %c %c")
 */
struct  _Movement
{
  ProtobufCMessage base;
  char *client_id;
  char *direction;
};
#define MOVEMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&movement__descriptor) \
    , NULL, NULL }


/*
 * Response from server (replaces simple string responses)
 */
struct  _ServerResponse
{
  ProtobufCMessage base;
  char *message;
};
#define SERVER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_response__descriptor) \
    , NULL }


/* Connect methods */
void   connect__init
                     (Connect         *message);
size_t connect__get_packed_size
                     (const Connect   *message);
size_t connect__pack
                     (const Connect   *message,
                      uint8_t             *out);
size_t connect__pack_to_buffer
                     (const Connect   *message,
                      ProtobufCBuffer     *buffer);
Connect *
       connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connect__free_unpacked
                     (Connect *message,
                      ProtobufCAllocator *allocator);
/* Movement methods */
void   movement__init
                     (Movement         *message);
size_t movement__get_packed_size
                     (const Movement   *message);
size_t movement__pack
                     (const Movement   *message,
                      uint8_t             *out);
size_t movement__pack_to_buffer
                     (const Movement   *message,
                      ProtobufCBuffer     *buffer);
Movement *
       movement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   movement__free_unpacked
                     (Movement *message,
                      ProtobufCAllocator *allocator);
/* ServerResponse methods */
void   server_response__init
                     (ServerResponse         *message);
size_t server_response__get_packed_size
                     (const ServerResponse   *message);
size_t server_response__pack
                     (const ServerResponse   *message,
                      uint8_t             *out);
size_t server_response__pack_to_buffer
                     (const ServerResponse   *message,
                      ProtobufCBuffer     *buffer);
ServerResponse *
       server_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_response__free_unpacked
                     (ServerResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Connect_Closure)
                 (const Connect *message,
                  void *closure_data);
typedef void (*Movement_Closure)
                 (const Movement *message,
                  void *closure_data);
typedef void (*ServerResponse_Closure)
                 (const ServerResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor connect__descriptor;
extern const ProtobufCMessageDescriptor movement__descriptor;
extern const ProtobufCMessageDescriptor server_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ship_5fmovement_2eproto__INCLUDED */
