/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ship_movement.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "../head/ship_movement.pb-c.h"
void   connect__init
                     (Connect         *message)
{
  static const Connect init_value = CONNECT__INIT;
  *message = init_value;
}
size_t connect__get_packed_size
                     (const Connect *message)
{
  assert(message->base.descriptor == &connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t connect__pack
                     (const Connect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t connect__pack_to_buffer
                     (const Connect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Connect *
       connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Connect *)
     protobuf_c_message_unpack (&connect__descriptor,
                                allocator, len, data);
}
void   connect__free_unpacked
                     (Connect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   movement__init
                     (Movement         *message)
{
  static const Movement init_value = MOVEMENT__INIT;
  *message = init_value;
}
size_t movement__get_packed_size
                     (const Movement *message)
{
  assert(message->base.descriptor == &movement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t movement__pack
                     (const Movement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &movement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t movement__pack_to_buffer
                     (const Movement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &movement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Movement *
       movement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Movement *)
     protobuf_c_message_unpack (&movement__descriptor,
                                allocator, len, data);
}
void   movement__free_unpacked
                     (Movement *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &movement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_response__init
                     (ServerResponse         *message)
{
  static const ServerResponse init_value = SERVER_RESPONSE__INIT;
  *message = init_value;
}
size_t server_response__get_packed_size
                     (const ServerResponse *message)
{
  assert(message->base.descriptor == &server_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_response__pack
                     (const ServerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_response__pack_to_buffer
                     (const ServerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerResponse *
       server_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerResponse *)
     protobuf_c_message_unpack (&server_response__descriptor,
                                allocator, len, data);
}
void   server_response__free_unpacked
                     (ServerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor connect__field_descriptors[1] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Connect, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned connect__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
};
static const ProtobufCIntRange connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Connect",
  "Connect",
  "Connect",
  "",
  sizeof(Connect),
  1,
  connect__field_descriptors,
  connect__field_indices_by_name,
  1,  connect__number_ranges,
  (ProtobufCMessageInit) connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor movement__field_descriptors[2] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Movement, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Movement, direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned movement__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  1,   /* field[1] = direction */
};
static const ProtobufCIntRange movement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor movement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Movement",
  "Movement",
  "Movement",
  "",
  sizeof(Movement),
  2,
  movement__field_descriptors,
  movement__field_indices_by_name,
  1,  movement__number_ranges,
  (ProtobufCMessageInit) movement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_response__field_descriptors[1] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerResponse, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_response__field_indices_by_name[] = {
  0,   /* field[0] = message */
};
static const ProtobufCIntRange server_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor server_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerResponse",
  "ServerResponse",
  "ServerResponse",
  "",
  sizeof(ServerResponse),
  1,
  server_response__field_descriptors,
  server_response__field_indices_by_name,
  1,  server_response__number_ranges,
  (ProtobufCMessageInit) server_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
