all: example-6

example-6: example-6.c
	gcc -g example-6.c -o example-6 \
	    -lSDL2 \
		-I/opt/homebrew/Cellar/sdl2/2.32.10/include \
		-L/opt/homebrew/Cellar/sdl2/2.32.10/lib

clean:
	rm -f example-6
