all: example-4

example-4: example-4.c
	gcc -g example-4.c -o example-4 \
		-lSDL2 -lSDL2_image \
		-I/opt/homebrew/Cellar/sdl2/2.32.10/include \
		-L/opt/homebrew/Cellar/sdl2/2.32.10/lib \
		-I/opt/homebrew/Cellar/sdl2/2.32.10/include/SDL2 \
		-L/opt/homebrew/Cellar/sdl2_image/2.8.8/lib \
		-I/opt/homebrew/Cellar/sdl2_image/2.8.8/include 

clean:
	rm -f example-4
